version: "3.8"
services:

  databas:
    image: mysql:5.7.30
    restart: always
    environment:
      - MYSQL_DATABASE=min_wiki
      - MYSQL_USER=wikiuser
      - MYSQL_PASSWORD=s3cr3t
      - MYSQL_ROOT_PASSWORD=supers3cr3t
    volumes:
      - ${PWD}/databas:/var/lib/mysql

  wiki:
    image: mediawiki:1.34.1
    restart: always
    depends_on:
      - databas
    volumes:
      - ${PWD}/LocalSettings.php:/var/www/html/LocalSettings.php
      - ${PWD}/images:/var/www/html/images
    ports:
      - 80:80
